version: '3'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
    - POSTGRES_USER=fibusr
    - POSTGRES_PASSWORD=fibpass
    - POSTGRES_DB=fibonacci_db
    volumes:
    - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
    - "5434:5432"
  redis:
    image: "redis:alpine"
    ports:
    - "6378:6379"
  web:
    build: ./web
    environment:
      FLASK_APP: run.py
      FLASK_CONFIG: production
    command: gunicorn --log-level info --log-file=/gunicorn.log --workers 4 --name fibo -b 0.0.0.0:8000 --reload run:app
    ports:
     - "8000:8000"
    depends_on:
    - postgres
    - redis

